version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile

    init: true
    volumes:
      - ../..:/workspaces:cached
      # https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-from-docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
