name: Deploy ailegis_api production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.job.yml

    with:
      DEPLOY_HOST: 165.232.114.97
      DEPLOY_USER: root
      DEPLOY_TRAEFIK_HOST: 'Host(`api.ailegis.com`)'
      OTEL_SERVICE_NAME: 'ailegis_api_service'
      # DEPLOY_KEY_FINGERPRINT: SHA256:6tY0y+NoSWn8Qg4ex/GFitMrrqkxnxZ5QfgxnUhsEco

    secrets:
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      # AZURE_FORM_RECOGNIZER_KEY: ${{ secrets.AZURE_FORM_RECOGNIZER_KEY }}
      # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
      NEON_DB_BASE_URL: ${{ secrets.NEON_DB_BASE_URL }}
